
set -g mouse on

# Bind Shift+Enter to send CSI u sequence
bind-key -n S-Enter send-keys Escape "[13;2u"

# Enable extended keys support
set -s extended-keys on

# Declare terminal supports extended keys
set -as terminal-features 'tmux-256color:extkeys'

unbind-key C-b              # free the original bind-key key
set-option -g prefix C-a    # setting the prefix from C-b to C-a
bind-key C-a send-prefix    # ensure that we can send Ctrl-A to other apps or the shell that your interacting
bind-key C-b source-file ~/.tmux.conf \; display "Config Reloaded !"

set-option -g base-index 1                # window index will start with 1
set-window-option -g pane-base-index 1    # pane index will start with 1
set-option -g renumber-windows on

bind-key | split-window -h -c "#{pane_current_path}" # let's open pane with current directory with -c option
bind-key _ split-window -v -c "#{pane_current_path}"

# Pane: Vim Style Movements
bind-key -r h select-pane -L              # go left
bind-key -r j select-pane -D              # go down
bind-key -r l select-pane -R              # go right
bind-key -r k select-pane -U              # go up

# Pane: Arrow Movements
bind-key Up select-pane -U
bind-key Down select-pane -D
bind-key Left select-pane -L
bind-key Right select-pane -R

# Window: Movements
bind-key L last-window
bind-key -r C-h select-window -t :-              # cycle through the windows for quick window selection
bind-key -r C-l select-window -t :+

# word separators for automatic word selection
set-window-option -g word-separators ' @"=()[]'  # default => ‘ -_@’.

# tmux adds a short, almost imperceptible delay between the commands that can cause funny behavior when running vim inside tmux.
set-option -s escape-time 0

# Set the default terminal mode to 256color mode
set -g default-terminal "screen-256color"

# Pane divider
set-window-option -g pane-border-style fg=colour11,bg=colour234
set-window-option -g pane-active-border-style fg=colour118,bg=colour234

# Cool trick: Let's dim out any pane that's not active.
# set-window-option -g window-style fg=white,bg=colour236
# set-window-option -g window-active-style fg=white,bg=colour235
set-window-option -g window-style fg=white,bg=default
set-window-option -g window-active-style fg=white,bg=default

# Command / Message line
set-window-option -g message-style fg=black,bold,bg=colour11

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'eduwass/tmux-palette'
set -g @palette-key 'C-Space'             # optional, default: C-Space (no-prefix)
set -g @palette-find-pane-key 'M-f'       # optional, no binding by default
set -g @palette-move-pane-key 'M-m'       # optional, no binding by default

set -g @plugin 'dracula/tmux'
set -g @dracula-show-powerline true
set -g @dracula-fixed-location 'Naga City'
set -g @dracula-plugins 'weather'
set -g @dracula-show-flags true
set -g @dracula-show-left-icon 'session'
set -g status-position top

bg=black

run '~/.tmux/plugins/tpm/tpm'
